name: Snyk Security Scan

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: . # root (where pom.xml exists)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # ✅ Run Snyk test (fail this step if vulnerabilities found, but continue workflow)
      - name: Snyk Test
        id: snyk-test
        run: snyk test --file=pom.xml --severity-threshold=medium --sarif-file-output=snyk.sarif
        continue-on-error: true

      # ✅ Monitor (always run, even if test failed)
      - name: Snyk Monitor
        if: always()
        run: snyk monitor --file=pom.xml || true

      # ✅ Upload SARIF report (always run)
      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      # ✅ Mark job as failed if vulnerabilities were found
      - name: Fail Job if Vulnerabilities Found
        if: steps.snyk-test.outcome == 'failure'
        run: exit 1
