name: Snyk Security Scan

on:
  workflow_dispatch:  # ✅ Allows manual run from Actions tab

jobs:
  snyk-sca:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Install Snyk CLI
      - name: Install Snyk
        run: npm install -g snyk

      # ✅ Authenticate with Snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # ✅ Run Snyk test (fail build if vulnerabilities >= medium severity)
      - name: Snyk Test for Maven
        run: snyk test --file=pom.xml --severity-threshold=medium --sarif-file-output=snyk.sarif

      # ✅ Send results to Snyk dashboard
      - name: Snyk Monitor
        run: snyk monitor --file=pom.xml

      # ✅ Upload SARIF to GitHub Security
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
