name: Snyk Security Scan

on:
  workflow_dispatch: # ✅ Manual trigger
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: . # root of repo (where pom.xml exists)

    steps:
      # ✅ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Set up Java for Maven projects
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Install Snyk CLI
      - name: Install Snyk
        run: npm install -g snyk

      # ✅ Authenticate Snyk using secret
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # ✅ Run Snyk test (generate SARIF, but DO NOT fail build)
      - name: Snyk Test
        run: snyk test --file=pom.xml --severity-threshold=medium --sarif-file-output=snyk.sarif || true

      # ✅ Send results to Snyk dashboard (Monitor)
      - name: Snyk Monitor
        run: snyk monitor --file=pom.xml || true

      # ✅ Upload SARIF to GitHub Security tab
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
